(library (sound (1))
  (export start set-dsp! hush!)
  (import (chezscheme) (prefix (soundio) soundio:))
  (define (silence time channel) 0.0)
  (define *sound-out* (soundio:open-default-out-stream silence))
  (define (set-dsp! f) (soundio:sound-out-write-callback-set! *sound-out* f))
  (define (hush!) (set-dsp! silence))
  (define (start) (soundio:start-out-stream *sound-out*))
  )
